Feature/market snapshot
parallel-finance/parallel-service pull request #66
Opened 2022-05-09 17:34 UTC by BruceChar

## Context

* Describe the changes made and why they were made.
 new getMarketStatus rpc to update market snapshot data
* Provide links to any issues or designs for this change.

## Were any new external packages added?

* List external packages added and why they were added

2022-05-10 01:41 UTC, zhihuizhangjaden commented on packages/app/src/service/job/mm/heiko/index.ts
> +  log.error(`heiko market snapshot`)
Why error?

2022-05-10 01:41 UTC, zhihuizhangjaden commented on packages/app/src/service/job/mm/index.ts
> +  // updateHeikoMarketSnapshot,
This is not needed?

2022-05-10 15:59 UTC, BruceChar commented on packages/app/src/service/job/mm/heiko/index.ts
> +  log.error(`heiko market snapshot`)
hah! is in progress just a local debug log has been deleted!

2022-05-10 16:01 UTC, BruceChar commented on packages/app/src/service/job/mm/index.ts
> +  // updateHeikoMarketSnapshot,
in progress local dev

2022-05-13 02:49 UTC, zhihuizhangjaden approved these changes
LGTM

2022-05-13 03:41 UTC, crystalynliu commented on packages/app/package.json
> +    "@parallel-finance/types": "^1.7.1",
upgrade to 1.7.3

2022-05-13 03:41 UTC, crystalynliu commented on packages/app/src/service/query.ts
> +      } as MarketSnapshot)
why need as here?

2022-05-13 03:50 UTC, BruceChar commented on packages/app/src/service/query.ts
> +      } as MarketSnapshot)
otherwise TS type check will failed

2022-05-13 03:52 UTC, crystalynliu commented on packages/app/src/service/query.ts
> +      } as MarketSnapshot)
So I think the issue is you are doing the wrong thing here, if the ts type cannot be passed, it means something wrong with your code.

2022-05-13 04:20 UTC, BruceChar commented on packages/app/src/service/query.ts
> +      } as MarketSnapshot)
It's 'cause the inject entity parameter is a `typeof BaseEntity`, the repository create need a specified Entity object.So typecast here

2022-05-13 06:16 UTC, xsteadybcgo requested changes

2022-05-13 07:15 UTC, BruceChar commented on packages/app/src/service/query.ts
> +    markets.map(assetId => statusQuery.push((this.api.rpc as any).loans.getMarketStatus(assetId)))
what's your point? see where the var used

2022-05-13 07:56 UTC, crystalynliu commented on packages/app/src/service/query.ts
> +      } as MarketSnapshot)
Okay, let us leave it now, but I think we can improve the type definition future.

2022-05-13 07:59 UTC, crystalynliu commented on packages/app/src/service/query.ts
> +    markets.map(assetId => statusQuery.push((this.api.rpc as any).loans.getMarketStatus(assetId)))
I think you can use `map` direct to generate statusQuery instead.
```
const statusQuery = markets.map(assetId => this.api.rpc.loans.getMarketStatus(assetId))
```

2022-05-13 09:44 UTC, xsteadybcgo approved these changes

2022-05-13 17:06 UTC, merged