remove unhandledRejection process.exit()
parallel-finance/parallel-service pull request #72
Opened 2022-05-13 03:45 UTC by BruceChar

## Context

* Describe the changes made and why they were made.
 remove service exit strategy when unhandledRejection & unexpected occurs
* Provide links to any issues or designs for this change.

## Were any new external packages added?

* List external packages added and why they were added

2022-05-13 03:50 UTC, zhihuizhangjaden approved these changes

2022-05-13 03:51 UTC, crystalynliu commented
I also see there is some `process.exit` in Redis and build script, could we remove it as well

2022-05-13 04:28 UTC, BruceChar commented
>
the build script only run in build process. it means some command run failed or incompletely we need to check the service make sure that the build is total successfully.

2022-05-13 04:30 UTC, BruceChar commented
if redis down, some api is unavailable.we need to catch the redis error and hold on

2022-05-13 06:11 UTC, xsteadybcgo requested changes

2022-05-13 06:11 UTC, xsteadybcgo commented on packages/app/src/index.ts
> +  if (type === 'unhandledRejection' && err.toString().includes('GraphQL Error')) {
Why not keep the call without passing arguments and put the logic for the callback function in the definition of the unexpectedListener function? Adding arguments here seems unnecessary, you only need to call the unexpectedListener once at the root level.

2022-05-13 07:18 UTC, BruceChar commented on packages/app/src/index.ts
> +  if (type === 'unhandledRejection' && err.toString().includes('GraphQL Error')) {
Just a expand reserve

2022-05-13 08:31 UTC, crystalynliu commented
> if redis down, some api is unavailable.we need to catch the redis error and hold on

@BruceChar I think we talked it in the meeting, we have a alert to know it. we don't need to shut down the service. We shouldn't shut down api service anyway.

2022-05-17 01:10 UTC, crystalynliu approved these changes

2022-05-17 03:21 UTC, xsteadybcgo approved these changes

2022-05-17 03:34 UTC, merged