Bte 130
parallel-finance/parallel-service pull request #78
Opened 2022-05-16 16:55 UTC by BruceChar

## Context

* Describe the changes made and why they were made.
Context:
 parallel service relys on subquery once the subquery network is down that parallel service api will be unavailable. 
Resolution:
 Add cache to prevent from api unavailable, it shouldn't crash if parallel service cannot fetch the latest data from third service.
* Provide links to any issues or designs for this change.

## Were any new external packages added?

* List external packages added and why they were added

2022-05-17 08:25 UTC, BruceChar commented
depart the pr into two pieces, 1. the redis util wrap restruct and add the cache file; 2. cache the subquery request

2022-05-17 09:18 UTC, crystalynliu commented on packages/app/package.json
> +    "aws-sdk": "^2.1094.0"
Remove the aws sdk dependencies

2022-05-17 09:18 UTC, crystalynliu commented on packages/app/src/service/redis.ts
> +enum DBT {
what's this enum for? Why do you not merge the `DBT { Graphql = 3 }` in one place?

2022-05-17 09:18 UTC, crystalynliu commented on packages/app/src/types/index.ts
> +export type NetworkT = 'PARA' | 'HEIKO' | 'heiko' | 'para'
why to support four network here?

2022-05-17 09:18 UTC, crystalynliu commented on packages/app/src/utils/cloudwatch.ts
> +export enum CloudWatchError {
Maybe remove the cloudwatch for now, we can create another card to do it

2022-05-17 09:41 UTC, BruceChar commented on packages/app/src/service/redis.ts
> +enum DBT {
it should be!

2022-05-17 09:42 UTC, BruceChar commented on packages/app/src/types/index.ts
> +export type NetworkT = 'PARA' | 'HEIKO' | 'heiko' | 'para'
eh! It's confused that only two network given four, I'll modify the usecase

2022-05-18 08:02 UTC, xsteadybcgo requested changes

2022-05-18 08:22 UTC, BruceChar commented on packages/lib/src/redis.ts
> +type DBT = number
it's in lib package just a alias

2022-05-18 08:23 UTC, BruceChar commented on packages/app/src/utils/config.ts
> +  static getEndpointsConfig(network: NetworkT = 'heiko'): EndpointConfig {
yes! for the database branch

2022-05-18 08:32 UTC, xsteadybcgo commented on packages/lib/src/redis.ts
> +type DBT = number
I think it is better to define `DBT` in the `@parallel/lib/src/redis.ts`,  and import this type from the '@parallel/lib'

2022-05-18 08:47 UTC, BruceChar commented on packages/lib/src/redis.ts
> +type DBT = number
the db is related to business, it cannot identify which db to use previously until we have a new requirement

2022-05-18 09:12 UTC, xsteadybcgo approved these changes

2022-05-18 09:28 UTC, merged