Bte 130 cache
parallel-finance/parallel-service pull request #86
Opened 2022-05-24 14:48 UTC by BruceChar

## Context

* Describe the changes made and why they were made.
 subquery request cache!
* Provide links to any issues or designs for this change.

## Were any new external packages added?

* List external packages added and why they were added
@pacote/option @pacote/result

2022-05-25 03:36 UTC, zhihuizhangjaden approved these changes
LGTM

2022-05-25 04:07 UTC, xsteadybcgo approved these changes

2022-05-25 07:18 UTC, BruceChar commented
@xsteadybcgo need your help to resolve the conflicts

2022-05-25 08:18 UTC, xsteadybcgo requested changes

2022-05-25 08:18 UTC, xsteadybcgo commented on packages/app/src/utils/subql.ts
> +    return Ok(`
Seem to be broken, does the `Ok` return the `string`? please check the endpoint in your local environment.

2022-05-27 04:53 UTC, BruceChar commented
why have 2 merges log? @xsteadybcgo

2022-05-27 05:34 UTC, xsteadybcgo approved these changes

2022-05-27 05:41 UTC, xsteadybcgo approved these changes

2022-05-27 05:41 UTC, xsteadybcgo commented on packages/app/src/utils/index.ts
> +  return result
I left a comment here, we need to discuss about this?

- what does the `%20` mean? 
- the `para` to `pair` ?
- what if passing a duplicate query key?

2022-05-27 05:45 UTC, xsteadybcgo commented
> why have 2 merges log? @xsteadybcgo

find some issue about the `asset_id`, i renamed it accidentally, the second one is a commit to fix it

2022-05-27 05:58 UTC, merged